---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_annotation
  title: grafana_annotation (resource)
  description: |
    resource `grafana_annotation` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/grafana-search-and-storage
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_contact_point
  title: grafana_contact_point (resource)
  description: |
    resource `grafana_contact_point` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/alerting-backend
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_dashboard
  title: grafana_dashboard (resource)
  description: |
    resource `grafana_dashboard` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/dashboards-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_dashboard_permission
  title: grafana_dashboard_permission (resource)
  description: |
    resource `grafana_dashboard_permission` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_dashboard_permission_item
  title: grafana_dashboard_permission_item (resource)
  description: |
    resource `grafana_dashboard_permission_item` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_dashboard_public
  title: grafana_dashboard_public (resource)
  description: |
    resource `grafana_dashboard_public` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/sharing-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_data_source
  title: grafana_data_source (resource)
  description: |
    resource `grafana_data_source` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/data-sources
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_data_source_config
  title: grafana_data_source_config (resource)
  description: |
    resource `grafana_data_source_config` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/data-sources
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_data_source_config_lbac_rules
  title: grafana_data_source_config_lbac_rules (resource)
  description: |
    resource `grafana_data_source_config_lbac_rules` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_data_source_permission
  title: grafana_data_source_permission (resource)
  description: |
    resource `grafana_data_source_permission` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_data_source_permission_item
  title: grafana_data_source_permission_item (resource)
  description: |
    resource `grafana_data_source_permission_item` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_folder
  title: grafana_folder (resource)
  description: |
    resource `grafana_folder` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/grafana-search-and-storage
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_folder_permission
  title: grafana_folder_permission (resource)
  description: |
    resource `grafana_folder_permission` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_folder_permission_item
  title: grafana_folder_permission_item (resource)
  description: |
    resource `grafana_folder_permission_item` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_library_panel
  title: grafana_library_panel (resource)
  description: |
    resource `grafana_library_panel` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/dataviz-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_message_template
  title: grafana_message_template (resource)
  description: |
    resource `grafana_message_template` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/alerting-backend
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_mute_timing
  title: grafana_mute_timing (resource)
  description: |
    resource `grafana_mute_timing` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/alerting-backend
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_notification_policy
  title: grafana_notification_policy (resource)
  description: |
    resource `grafana_notification_policy` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/alerting-backend
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_organization
  title: grafana_organization (resource)
  description: |
    resource `grafana_organization` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_organization_preferences
  title: grafana_organization_preferences (resource)
  description: |
    resource `grafana_organization_preferences` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_playlist
  title: grafana_playlist (resource)
  description: |
    resource `grafana_playlist` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/sharing-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_report
  title: grafana_report (resource)
  description: |
    resource `grafana_report` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/sharing-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_role
  title: grafana_role (resource)
  description: |
    resource `grafana_role` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_role_assignment
  title: grafana_role_assignment (resource)
  description: |
    resource `grafana_role_assignment` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_role_assignment_item
  title: grafana_role_assignment_item (resource)
  description: |
    resource `grafana_role_assignment_item` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_rule_group
  title: grafana_rule_group (resource)
  description: |
    resource `grafana_rule_group` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/alerting-backend
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_service_account
  title: grafana_service_account (resource)
  description: |
    resource `grafana_service_account` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_service_account_permission
  title: grafana_service_account_permission (resource)
  description: |
    resource `grafana_service_account_permission` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_service_account_permission_item
  title: grafana_service_account_permission_item (resource)
  description: |
    resource `grafana_service_account_permission_item` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_service_account_rotating_token
  title: grafana_service_account_rotating_token (resource)
  description: |
    resource `grafana_service_account_rotating_token` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_service_account_token
  title: grafana_service_account_token (resource)
  description: |
    resource `grafana_service_account_token` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_sso_settings
  title: grafana_sso_settings (resource)
  description: |
    resource `grafana_sso_settings` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_team
  title: grafana_team (resource)
  description: |
    resource `grafana_team` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_team_external_group
  title: grafana_team_external_group (resource)
  description: |
    resource `grafana_team_external_group` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/access-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_scim_config
  title: grafana_scim_config (resource)
  description: |
    resource `grafana_scim_config` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_user
  title: grafana_user (resource)
  description: |
    resource `grafana_user` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/identity-squad
  lifecycle: production
